jwt:
    secret: ${JWT_SECRET}

refreshtoken:
    secret: ${REFRESH_TOKEN_SECRET}

server:
    error:
        include-message: always
    port: 8080
    forward-headers-strategy: framework
    http2:
        enabled: true

spring:
    graphql:
        cors:
            allowed-origins:
                - https://localhost
                - http://localhost
                - http://localhost:8080
                - https://localhost:8080
    datasource:
        url: jdbc:postgresql://postgres:5432/mydatabase
        username: myuser
        password: secret
    jackson:
        serialization:
            fail-on-empty-beans: false
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
    mvc:
        servlet:
            load-on-startup: 1
    data:
        redis:
            repositories:
                enabled: false
            host: redis

management:
    endpoint:
        health:
            enabled: true

logging:
    level:
        org:
            springframework:
                web:
                    servlet:
                        DispatcherServlet: DEBUG
                    filter:
                        CorsFilter: DEBUG
                    HandlerMapping: DEBUG
                    HandlerExecutionChain: DEBUG