jwt:
    secret: ${JWT_SECRET}
server:
    error:
        include-message: always
    port: 8080
spring:
    graphql:
        cors:
            allow-credentials: true
            allowed-origins:
                - http://localhost:5173
                - http://127.0.0.1:5173
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: example
    jackson:
        serialization:
            fail-on-empty-beans: false
    jpa:
        hibernate:
            ddl-auto: update