jwt:
    secret: ${JWT_SECRET}
server:
    error:
        include-message: always
    port: 8080

    forward-headers-strategy: framework
    http2:
        enabled: true
spring:
    graphql:
        # TODO: With Traefik, allowed origins must be set to the domain name of the frontend
        cors:
            allow-credentials: true
            allowed-origins:
                - https://localhost
    datasource:
        url: jdbc:postgresql://postgres:5432/postgres
        username: postgres
        password: example
    jackson:
        serialization:
            fail-on-empty-beans: false
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
    mvc:

        servlet:
            load-on-startup: 1
    data:
        redis:
            repositories:
                enabled: false
management:
    endpoint:
        health:
            enabled: true