name: CI Tests

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build:
        permissions: write-all
        runs-on: self-hosted
        steps:
            -   uses: actions/checkout@v3

            -   name: Set up JDK 20
                uses: actions/setup-java@v3
                with:
                    java-version: '20'
                    distribution: 'corretto'
                    cache: maven
            -   name: Build with Maven
                run: mvn -B package --file pom.xml -DskipTests

            -   name: Update dependency graph
                uses: advanced-security/maven-dependency-submission-action@c5ad0fd6b977364190852883b46728f25a9617c3
                env:
                    PATH: ${{ runner.tool_cache }}/jdk/20/x64/bin:${PATH}
    unit-tests:
        needs: build
        permissions: write-all
        runs-on: self-hosted

        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK 20
                uses: actions/setup-java@v3
                with:
                    java-version: '20'
                    distribution: 'corretto'
                    cache: maven
            -   name: Stop existing postgres and redis
                run: docker compose --profile test down

            -   name: Start postgres and redis
                run: docker compose --profile test up -d

            -   name: Run unit tests
                run: mvn -B test --file pom.xml

            -   name: Stop postgres and redis
                run: docker compose --profile test down