name: CI Tests

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build:
        permissions: write-all
        runs-on: self-hosted
        steps:
            -   uses: actions/checkout@v4

            -   name: Set up GraalVM 21 JDK
                uses: graalvm/setup-graalvm@v1
                with:
                    java-version: '21'
                    distribution: 'graalvm'
                    cache: 'maven'
                    check-for-updates: true

            -   name: Build with Maven
                run: mvn -B -DskipTests -Pnative package --file pom.xml

            -   name: Update dependency graph
                uses: advanced-security/maven-dependency-submission-action@v3.0.2
    unit-tests:
        needs: build
        permissions: write-all
        runs-on: self-hosted

        steps:
            -   uses: actions/checkout@v4

            -   name: Set up GraalVM 21 JDK
                uses: graalvm/setup-graalvm@v1
                with:
                    java-version: '21'
                    distribution: 'graalvm'
                    cache: 'maven'
                    check-for-updates: true

            -   name: Stop existing postgres and redis
                run: docker compose --profile test down

            -   name: Start postgres and redis
                run: docker compose --profile test up -d

            -   name: Run unit tests
                run: mvn -B -PnativeTest test --file pom.xml

            -   name: Stop postgres and redis
                run: docker compose --profile test down