name: CI Tests

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build:
        permissions: write-all
        runs-on: self-hosted
        steps:
            -   uses: actions/checkout@v3

            -   name: Set up JDK 20
                uses: actions/setup-java@v3
                with:
                    java-version: '20'
                    distribution: 'corretto'
                    cache: maven
            -   name: Build with Maven
                run: mvn -B package --file pom.xml -DskipTests

            -   name: Update dependency graph
                uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
    unit-tests:
        needs: build
        permissions: write-all
        runs-on: self-hosted

        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK 20
                uses: actions/setup-java@v3
                with:
                    java-version: '20'
                    distribution: 'corretto'
                    cache: maven
            -   name: Stop existing postgres and redis
                run: docker compose --profile test down

            -   name: Start postgres and redis
                run: docker compose --profile test up -d

            -   name: Run unit tests
                run: mvn -B test --file pom.xml

            -   name: Stop postgres and redis
                run: docker compose --profile test down