name: CI Tests

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build-doc:
        permissions: write-all
        runs-on: self-hosted
        steps:
            -   uses: actions/checkout@v4

            -   name: Set up GraalVM 21 JDK
                uses: graalvm/setup-graalvm@v1
                with:
                    java-version: '21'
                    distribution: 'graalvm'
                    cache: 'maven'
                    check-for-updates: true

            -   name: Build Javadoc
                run: mvn -B javadoc:javadoc --file pom.xml
    build:
        permissions: write-all
        runs-on: self-hosted
        steps:
            -   uses: actions/checkout@v4

            -   name: Set up GraalVM 21 JDK
                uses: graalvm/setup-graalvm@v1
                with:
                    java-version: '21'
                    distribution: 'graalvm'
                    cache: 'maven'
                    check-for-updates: true

            -   name: Check if Docker is running, if not start it
                run: |
                    if ! docker info > /dev/null 2>&1; then
                                            open -a Docker && sleep 20
                    fi

            -   name: Build with Maven
                run: mvn -B -DskipTests -Pnative package --file pom.xml

            -   name: Update dependency graph
                uses: advanced-security/maven-dependency-submission-action@v3.0.3
    unit-tests:
        needs: build
        permissions: write-all
        runs-on: self-hosted

        steps:
            -   uses: actions/checkout@v4

            -   name: Set up GraalVM 21 JDK
                uses: graalvm/setup-graalvm@v1
                with:
                    java-version: '21'
                    distribution: 'graalvm'
                    cache: 'maven'
                    check-for-updates: true

            -   name: Check if Docker is running, if not start it
                run: |
                    if ! docker info > /dev/null 2>&1; then
                                            open -a Docker && sleep 20
                    fi

            -   name: Stop existing postgres and redis
                run: docker compose -f compose.test.yaml down

            -   name: Start postgres and redis
                run: docker compose -f compose.test.yaml up -d

            -   name: Set test.env in environment
                run: cat test.env >> $GITHUB_ENV

            -   name: Run Unit Tests
                run: mvn -B test --file pom.xml

            -   name: Stop Postgres and Redis
                run: docker compose -f compose.test.yaml down
